import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

// Mapeamento inteligente de tags para categorias - Expandido para perfil de usuário
const tagCategoryMapping: { [key: string]: string } = {
   // === CATEGORIAS DE PERFIL DE USUÁRIO ===

   // Tipo de Conteúdo
   Fotos: "Tipo de Conteúdo",
   Vídeos: "Tipo de Conteúdo",
   Stories: "Tipo de Conteúdo",
   Reels: "Tipo de Conteúdo",
   Lives: "Tipo de Conteúdo",
   Blog: "Tipo de Conteúdo",
   "Blog Posts": "Tipo de Conteúdo",
   Reviews: "Tipo de Conteúdo",
   Unboxing: "Tipo de Conteúdo",
   Tutorial: "Tipo de Conteúdo",
   Vlog: "Tipo de Conteúdo",
   Podcast: "Tipo de Conteúdo",
   Artigo: "Tipo de Conteúdo",
   Post: "Tipo de Conteúdo",
   Foto: "Tipo de Conteúdo",
   Vídeo: "Tipo de Conteúdo",
   Story: "Tipo de Conteúdo",
   Reel: "Tipo de Conteúdo",
   Live: "Tipo de Conteúdo",

   // Nicho de Atuação
   Moda: "Nicho de Atuação",
   Beleza: "Nicho de Atuação",
   Tecnologia: "Nicho de Atuação",
   Saúde: "Nicho de Atuação",
   Gastronomia: "Nicho de Atuação",
   Turismo: "Nicho de Atuação",
   Lifestyle: "Nicho de Atuação",
   Jogos: "Nicho de Atuação",
   Educação: "Nicho de Atuação",
   Negócios: "Nicho de Atuação",
   Empreendedorismo: "Nicho de Atuação",
   Arte: "Nicho de Atuação",
   Cultura: "Nicho de Atuação",
   Música: "Nicho de Atuação",
   Cinema: "Nicho de Atuação",
   Literatura: "Nicho de Atuação",
   Esportes: "Nicho de Atuação",
   Automóveis: "Nicho de Atuação",
   Pets: "Nicho de Atuação",
   Animais: "Nicho de Atuação",
   Decoração: "Nicho de Atuação",
   Arquitetura: "Nicho de Atuação",
   Maternidade: "Nicho de Atuação",
   Paternidade: "Nicho de Atuação",
   Família: "Nicho de Atuação",
   Casamento: "Nicho de Atuação",
   Relacionamento: "Nicho de Atuação",
   Finanças: "Nicho de Atuação",
   Investimentos: "Nicho de Atuação",
   Produtividade: "Nicho de Atuação",
   "Desenvolvimento Pessoal": "Nicho de Atuação",
   Meditação: "Nicho de Atuação",
   Yoga: "Nicho de Atuação",
   "Bem-estar": "Nicho de Atuação",
   Sustentabilidade: "Nicho de Atuação",
   "Meio Ambiente": "Nicho de Atuação",
   Política: "Nicho de Atuação",
   Atualidades: "Nicho de Atuação",
   Comédia: "Nicho de Atuação",
   Humor: "Nicho de Atuação",

   // Público-Alvo
   Adolescentes: "Público-Alvo",
   Jovens: "Público-Alvo",
   Adultos: "Público-Alvo",
   Pais: "Público-Alvo",
   Mães: "Público-Alvo",
   Profissionais: "Público-Alvo",
   Estudantes: "Público-Alvo",
   Empreendedores: "Público-Alvo",
   Executivos: "Público-Alvo",
   Freelancers: "Público-Alvo",
   Idosos: "Público-Alvo",
   Crianças: "Público-Alvo",
   Mulheres: "Público-Alvo",
   Homens: "Público-Alvo",
   "LGBTQ+": "Público-Alvo",
   Casais: "Público-Alvo",
   Solteiros: "Público-Alvo",
   Universitários: "Público-Alvo",
   "Jovens Adultos": "Público-Alvo",

   // Plataformas
   Instagram: "Plataformas",
   YouTube: "Plataformas",
   TikTok: "Plataformas",
   Facebook: "Plataformas",
   Twitter: "Plataformas",
   LinkedIn: "Plataformas",
   Pinterest: "Plataformas",
   Twitch: "Plataformas",
   Spotify: "Plataformas",
   Snapchat: "Plataformas",
   WhatsApp: "Plataformas",
   Telegram: "Plataformas",
   Discord: "Plataformas",
   Reddit: "Plataformas",
   Medium: "Plataformas",
   Substack: "Plataformas",
   OnlyFans: "Plataformas",
   Patreon: "Plataformas",

   // Tipos de Colaboração
   "Posts Patrocinados": "Tipos de Colaboração",
   Takeovers: "Tipos de Colaboração",
   Eventos: "Tipos de Colaboração",
   "Criação de Conteúdo": "Tipos de Colaboração",
   Branding: "Tipos de Colaboração",
   Marketing: "Tipos de Colaboração",
   Publicidade: "Tipos de Colaboração",
   Parceria: "Tipos de Colaboração",
   Afiliação: "Tipos de Colaboração",
   Ambassador: "Tipos de Colaboração",
   Embaixador: "Tipos de Colaboração",
   Influencer: "Tipos de Colaboração",
   UGC: "Tipos de Colaboração",
   "User Generated Content": "Tipos de Colaboração",

   // Especialidades
   Fotografia: "Especialidades",
   "Edição de Vídeo": "Especialidades",
   Copywriting: "Especialidades",
   "Marketing Digital": "Especialidades",
   Design: "Especialidades",
   "Estratégia de Conteúdo": "Especialidades",
   Analytics: "Especialidades",
   "Growth Hacking": "Especialidades",
   SEO: "Especialidades",
   SEM: "Especialidades",
   "Social Media": "Especialidades",
   "Redes Sociais": "Especialidades",
   "Produção de Vídeo": "Especialidades",
   "Edição de Imagem": "Especialidades",
   Ilustração: "Especialidades",
   Animação: "Especialidades",
   "Motion Graphics": "Especialidades",
   "Web Design": "Especialidades",
   "UI/UX": "Especialidades",
   Programação: "Especialidades",
   Desenvolvimento: "Especialidades",
   Consultoria: "Especialidades",
   Mentoria: "Especialidades",
   Coaching: "Especialidades",
   Treinamento: "Especialidades",
   Palestras: "Especialidades",
   Workshops: "Especialidades",
   Cursos: "Especialidades",
   "E-books": "Especialidades",
   Podcasts: "Especialidades",
   Streaming: "Especialidades",
   Gaming: "Especialidades",
   Cosplay: "Especialidades",
   Maquiagem: "Especialidades",
   Cabelo: "Especialidades",
   Skincare: "Especialidades",
   Fitness: "Especialidades",
   Nutrição: "Especialidades",
   Culinária: "Especialidades",
   Viagem: "Especialidades",
   "Fotografia de Viagem": "Especialidades",
   Videografia: "Especialidades",
   Drone: "Especialidades",
   "Fotografia Aérea": "Especialidades",

   // === CATEGORIAS EXISTENTES (Design/Arquitetura) ===

   // Estilos e Design
   Minimalismo: "Tendências de Design",
   Escandinavo: "Tendências de Design",
   Industrial: "Tendências de Design",
   Vintage: "Tendências de Design",
   Moderno: "Tendências de Design",
   Rústico: "Tendências de Design",
   Luxo: "Tendências de Design",
   Elegante: "Estilos Decorativos",
   Madeira: "Materiais Naturais",
   Mármore: "Materiais Naturais",
   Concreto: "Materiais Naturais",
   Vidro: "Materiais Sintéticos",
   Metal: "Materiais Sintéticos",
   Tecido: "Tecidos e Tecelagens",
   Sustentável: "Tecnologia Sustentável",
   Natural: "Materiais Sustentáveis",
   "Smart Home": "Automação Residencial",
   LED: "Iluminação",
   Ergonômico: "Ergonomia",
   Funcional: "Multifuncionalidade",
};

const DEFAULT_CATEGORY = "Perfil de Usuário";

export async function autoCategorizeTag(tagName: string): Promise<number> {
   const categoryName = tagCategoryMapping[tagName] || DEFAULT_CATEGORY;
   let category = await prisma.tagCategory.findFirst({ where: { name: categoryName } });
   if (!category) {
      category = await prisma.tagCategory.create({ data: { name: categoryName } });
   }
   return category.id;
}
