export const dexdStorePayload = {
   name: "Dexd",
   surname: "Store",
   identification: "11.222.333/0001-44",
   phone: "9111222333",
   cellphone: "94445556667",
   birthDate: new Date("2000/01/01"),
   email: "dexdstore@dexd.com.br",
   profilePicture: "https://picsum.photos/965/575",
   password: "dexdstore2023",
   stateRegistration: "SP",
   serviceType: "loja",
   companyName: "Dexd Store - Loja Oficial LTDA",
   tradingName: "Dexd Store",
   type: "loja",
   address: {
      neighborhood: "Centro",
      street: "teste",
      number: "123",
      zipcode: "12345678",
      city: "São Paulo",
      state: "São Paulo",
      country: "Brasil",
      uf: "SP",
   },
   tags: [],
   role: "loja",
};
