export const measurementUnits = [
  { code: 'un', description: 'Unidade' },
  { code: 'pct', description: 'Pacote' },
  { code: 'cx', description: 'Caixa' },
  { code: 'kit', description: 'Kit' },
  { code: 'par', description: 'Par' },
  { code: 'dúzia', description: 'Dúzia' },
  { code: 'cento', description: 'Cento' },
  { code: 'milheiro', description: 'Milheiro' },
  { code: 'm', description: 'Metro' },
  { code: 'm²', description: 'Metro Quadrado' },
  { code: 'm³', description: 'Metro Cúbico' },
  { code: 'cm', description: 'Centímetro' },
  { code: 'mm', description: 'Milímetro' },
  { code: 'L', description: 'Litro' },
  { code: 'ml', description: 'Mililitro' },
  { code: 'kg', description: 'Quilograma' },
  { code: 'g', description: 'Grama' },
  { code: 'mg', description: 'Miligrama' },
  { code: 'rolo', description: 'Rolo' },
  { code: 'tubo', description: 'Tubo' },
  { code: 'frasco', description: 'Frasco' },
  { code: 'pote', description: 'Pote' },
  { code: 'lata', description: 'Lata' },
  { code: 'saco', description: 'Saco' },
  { code: 'fardo', description: 'Fardo' },
  { code: 'garrafa', description: 'Garrafa' },
  { code: 'painel', description: 'Painel' },
  { code: 'placa', description: 'Placa' },
  { code: 'chapa', description: 'Chapa' },
  { code: 'metro linear', description: 'M Linear' },
];
